# Abrix
options: 
  NAME: &e&lAbrix&7>
  STATS: &e&lAbrix&6&lStats
  VERSION: &e1.0 &cDEV
  ABRIX: &e&lAbrix
  WEBSITE: google.com
  
on join: 
 message "{@NAME} &cAnti-Cheat &aLoaded"
 message "&7Sub-plugin of &6&lCamCraft"
 message "&e----------------------------"
 

command /pl: 
 trigger:
  kick the player due to "{@NAME} &cYou cannot use /pl"
  

command /abrixstats <player>: 
 trigger: 
  message "&b---{@STATS}&b---"
  if argument 1 is in gamemode survival: 
  message "&7Gamemode: &eSurvival" 
  if argument 1 is in gamemode creative: 
  message "&7Gamemode: &eCreative"
  if argument 1 is op: 
  message "&c: OP: &6True" 
     
     
command /warn <player> <texts>:
 trigger:
  message "{@NAME}&eYou &ewarned player &9%arg 1% &efor &f%arg 2%"
  log "%player% reported %arg 1% for %arg 2%" to "reports/reports"
  loop all players:
   if loop-player has permission "abrix.showstaffreport":
   send "{@NAME} &6%player% &eissued a friendly warning to %arg-1%." to loop-player
   
   
command /abrix: 
 trigger: 
  message "&b---&6&lAbout {@ABRIX}&b---"
  message "&aVersion: {@VERSION}"
  message "&9Server Time: &5%now%"
  
  
command /kick <player> <text>: 
 trigger: 
  message "{@NAME} Kicking player &c%arg 1% &7for &f%arg 2%"
  kick argument 1 due to "{@NAME} &cKicked due to %arg 2% || &bSomething wrong? Report it at {@WEBSITE}"
  
  
  